#!/bin/sh
# Get the configuration value
. /CONF

# Setup BEE dependencies and environment.
if ! [ -d /data/venv ]
then
    # Create a virtualenv in /data/venv if the /data/venv directory does not
    # exist yet.
    python -m venv /data/venv
    . /data/venv/bin/activate
    pip install poetry
    cd /data/$BEE_REPO_DIR
    poetry update
    poetry install
fi
