#!/bin/sh
# Get the configuration value
. /CONF

# Setup BEE dependencies and environment.
# TODO: This is quite messy and needs to be cleaned up somehow
if ! [ -d /data/venv ]
then
    # Create a virtualenv in /data/venv if the /data/venv directory does not
    # exist yet.
    python -m venv /data/venv
    . /data/venv/bin/activate
    pip install poetry
    cd /data/$BEE_REPO_DIR
    poetry install
    poetry run sh <<EOF
pip install Cython
cd /tmp
git clone https://github.com/PySlurm/pyslurm.git
cd pyslurm
git checkout 19.05.0
python setup.py build
python setup.py install
pip list
EOF
fi
