#!/bin/sh
# Use this script to shut down the container

. ./CONF

# TODO: This will not work if more than one docker image is running
# at a time
CONTAINER_ID=$(docker ps | head -n 2 | tail -n 1 | cut -d' ' -f1)
docker kill $CONTAINER_ID

